version: '3'
services:
    api:
        container_name: dev_api
        image: python:latest
        working_dir: /code
        volumes:
            - type: bind
              source: ./api
              target: /code
        ports:
            - 5000:3000
        environment:
            - PGUSER=quizz_team
            - PGHOST=db
            - PGPASSWORD=countdownpass
            - PGDATABASE=quizz_db
            - PGPORT=5432
            - NODE_ENV=development
        depends_on:
            - db
        command: bash -c "pipenv shell && pipenv install && pipenv dev"

    db:
        container_name: dev_db
        image: postgres:latest
        environment:
            - POSTGRES_USER=quizz_team
        volumes:
            - './db:/docker-entrypoint-initdb.d/:ro'
        environment:
            - POSTGRES_DB=quizz_db
            - POSTGRES_USER=quizz_team
            - POSTGRES_PASSWORD=countdownpass

volumes:
    dbdata:
